menu:
    Blog: /
    Archive: /archives/
    Weibo: http://weibo.com/zeroibc
    GitHub: https://github.com/zeroibc
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus: seansun
duoshuo:

# Analytics
# google-analytics:
# ga: UA-xxxxxxxx-x

# Copyright Infomation
startyear: 2017
